FROM node:20-alpine as build

WORKDIR /app

ADD package.json /app/package.json

RUN npm i -g pnpm

RUN apk update && apk add --no-cache git
RUN pnpm install

ADD . /app

RUN npm run web:build

FROM node:20-alpine
WORKDIR /app

RUN npm i -g pnpm
ADD package.json /app/package.json

COPY --from=build app/dist/apps/web /app

RUN apk update && apk add --no-cache git
RUN pnpm install -P

CMD ["npm", "start"]