export enum EnvironmentVariablesEnum {
  MONGO_URL = "MONGO_URL",
  DATABASE_NAME = "DATABASE_NAME",
  JWT_SECRET = "JWT_SECRET",
  MINIO_ENDPOINT = "MINIO_ENDPOINT",
  MINIO_PORT = "MINIO_PORT",
  MINIO_ACCESS_KEY = "MINIO_ACCESS_KEY",
  MINIO_SECRET_KEY = "MINIO_SECRET_KEY",
  MINIO_BUCKET = "MINIO_BUCKET",
  REDIS_HOST = "REDIS_HOST",
  REDIS_PORT = "REDIS_PORT",
}
