export enum EnvironmentVariablesEnum {
  MONGO_URL = "MONGO_URL",
  DATABASE_NAME = "DATABASE_NAME",
  JWT_SECRET = "JWT_SECRET",
  GOOGLE_CLIENT_ID = "GOOGLE_CLIENT_ID",
  GOOGLE_CLIENT_SECRET = "GOOGLE_CLIENT_SECRET",
  SERVER_URL = "SERVER_URL",
}
